---
version: "3"
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/:/etc/ssl/
    networks:
      - api-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - api-network

  ipstack1:
    image: dilshdakp/ipstack:v1
    container_name: ipstack1
    restart: always
    environment:
      - CACHING_SERVER=redis
      - IPSTACK_KEY=0ee0d22e449bbe0a1c8af1f9d2ce8a9a

    networks:
      - api-network

  ipstack2:
    image: dilshadkp/ipstack:v1
    container_name: ipstack2
    restart: always
    environment:
      - CACHING_SERVER=redis
      - IPSTACK_KEY=0ee0d22e449bbe0a1c8af1f9d2ce8a9a

    networks:
      - api-network

  ipstack3:
    image: dilshadkp/ipstack:v1
    container_name: ipstack3
    restart: always
    environment:
      - CACHING_SERVER=redis
      - IPSTACK_KEY=0ee0d22e449bbe0a1c8af1f9d2ce8a9a

    networks:
      - api-network


networks:
  api-network:
